### ISSUE TITLE
ffmpeg.exe is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Kepee** [untoor/Ruutu-lataaja#1]
Videon lataaminen stoppaa otsikon virheviestiin.

![Capture](https://user-images.githubusercontent.com/21184964/66245303-a16b3d00-e715-11e9-91f6-ddb3456d22ce.PNG)
![Capture2](https://user-images.githubusercontent.com/21184964/66245304-a16b3d00-e715-11e9-87ca-4170d4f596cd.PNG)

**Comment by untoor** [comment]
Kiitos infosta ja pahoittelut että vastaukseni tulee nyt vasta. Johtuen siitä kun ruutu+ -videoihin tuli tuon Suplan lisäyksen aikaan muutos niin jätin ohjelman päivityksen siihen paikkaan. Mutta nyt olen tässä lähiaikoina juur korjaillut mitä muutoksia on ilmennyt ja betatestauttanut muutamalla henkilöllä.

Tuossa oli virheenä ffmpeg:n oikea polku. On korjattu. Ja julkaisen uuden version tänään.

**Comment by untoor** [comment]
> 
> 
> Videon lataaminen stoppaa otsikon virheviestiin.
> 
> ![Capture](https://user-images.githubusercontent.com/21184964/66245303-a16b3d00-e715-11e9-91f6-ddb3456d22ce.PNG)
> ![Capture2](https://user-images.githubusercontent.com/21184964/66245304-a16b3d00-e715-11e9-87ca-4170d4f596cd.PNG)

Kiitos infosta ja pahoittelut että vastaukseni tulee nyt vasta. Johtuen siitä kun ruutu+ -videoihin tuli tuon Suplan lisäyksen aikaan muutos niin jätin ohjelman päivityksen siihen paikkaan. Mutta nyt olen tässä lähiaikoina juur korjaillut mitä muutoksia on ilmennyt ja betatestauttanut muutamalla henkilöllä.

Tuossa oli virheenä ffmpeg:n oikea polku. On korjattu. Ja julkaisen uuden version tänään.
