### ISSUE TITLE
En voi ladata mitään plussa juttuja

### ISSUE THREAD

**Issue by Jukkis210** [untoor/Ruutu-lataaja#10]
Moron.

Onkohan nelonen jotain muuttanut kun en voi enään ladata ruutu+ ohjelmia?
Kokeilin sekä chromella että firefoxilla. Chrome antanut enään token gatlingia?

**Comment by untoor** [comment]
@Jukkis210 Juu ovat, gatlingia ei tällä hetkellä löydy, ovat sen taas rikkoneet. Aiemminkin ollut näin. Mutta plussan alaisten ohjelmien linkki ilmestyy kyllä näkyviin jotenka tarttee tällä hetkellä manuaalisesti kirjotella latausrimpsu komentoriville. Voisin tähän tehdä vastaisuuksien varalle väliaikaislaatajan jota voisi käytellä tälläisissä tilanteissa.

**Comment by Jukkis210** [comment]
Onko se rimpsu vaikea itse laitella?
Ja sellainen väliaikaislataaja olis varmaan kova juttu :)

**Comment by untoor** [comment]
@Jukkis210 Noo netistä löytyy vinkit siihen mutta helpotan teidän urakkaa siten että teen sen ohjelman suoraan ja siihen ohjeet. Ilmestyy tänään.

**Comment by untoor** [comment]
Uusi versio julki, ohjeissa tiedot.

**Comment by Jukkis210** [comment]
Itsellä ainakin lopettaa aivan samantien kun aloitan lataamaan. Heti tulee viesti, että haluatko ladata uuden jakson.
Pitää hieman tutkia asiaa kun tulen kaupasta. Kiitoksia kuitenkin tästä.

**Comment by untoor** [comment]
@Jukkis210 Ahaa, testaanpa toisella koneella kans.

**Comment by Jukkis210** [comment]
Nyt kun luin ajatuksella niin toimii :)
Kopsasin meinaan aluksi vain sen tokenin jälkeen olevan rimpsun :/

**Comment by untoor** [comment]
Noni hyvä juttu.
Aa okei.
