### ISSUE TITLE
Ei toimi?

### ISSUE THREAD

**Issue by outoffit** [untoor/Ruutu-lataaja#11]
Uusimman Ruutu-sijaislataajan avatessa command linessa teksti:
"Määritettyä polkua ei löydy.
Määritettyä tiedostoa ei löydy.
Uusi versio saatavilla!

Sulje ikkuna painamalla painiketta ja lataa uusin versio Githubista."

Uusin veriso on siis ladattu, mitään ei voi liittää command lineen, koska sulkee sen.

**Comment by untoor** [comment]
@outoffit Tarkista että lataaja on samassa kansiossa kuin se virallinenkin. Polut on ohjelmassa kunnossa, varmistin ne.

**Comment by untoor** [comment]
@outoffit Juu. Outoa. Onko sulla 10 vai 11 käyttiksenä?

**Comment by untoor** [comment]
Juu, oon kerran sen 11 laittanu valmiiks ja meni hetki et löyty sama alkusijainti mitä 10. Nii sun tarttee laittaa täysin samaan polkuun siinä 11 mitä 10 on. Sit se toimii.

**Comment by outoffit** [comment]
En oo ihan varma mitä tarkoitat.
Mulla on kansion polkuna "C:\Ruutu", pitäiskö sen olla jokin muu?

**Comment by untoor** [comment]
Juu tuossa on puutoksia, et täytyy olla tämä sama mikä etusivullakin lukee eli "C:\Users\Käyttäjänimi\Ruutu" , sitten pelittää.

**Comment by outoffit** [comment]
Okei, kiitos.

Jostain syystä jäänyt toi kohta lukematta tai en tajunnut laittaa käyttäjänimen alle. 
Nyt toimii kyllä hyvin.

**Comment by untoor** [comment]
Noni hieno homma 👍🏼 Suljen tän tapauksen.
