### ISSUE TITLE
Useiden tiedostojen lataaminen automaattisesti

### ISSUE THREAD

**Issue by apinanaivot** [untoor/Ruutu-lataaja#12]
Hei, hyvä ominaisuus lisätä olisi mahdollisuus ladata useita tiedostoja kerralla, ilman että tarvitsee syöttää jokaisen tietoja erikseen ja istua koneella odottamassa latauksia yksi kerrallaan. Se voisi toimia esim niin että olisi tekstitiedosto, jossa ohjelmat joita haluaa ladata olisi esim näin:

```
https://www.ruutu.fi/video/4420316|Sipoon Herttua S1E1
https://www.ruutu.fi/video/4420313|Sipoon Herttua S1E2
```

Ja sitten batch-lataajan suorittaminen lataisi nuo videot automaattisesti ja nimeäisi ne |:n oikealla puolella olevan tekstin mukaan.

**Comment by untoor** [comment]
@apinanaivot Moro, kiitos ideasta, laitetaan kehitykseen. Maksullisen sisällön kohdalla tarvii edelleen yksitellen ladata.
