### ISSUE TITLE
Ongelma lataamisessa

### ISSUE THREAD

**Issue by jypinen** [untoor/Ruutu-lataaja#2]
Hei,

Kiitos hyvän idean työkalusta. Kuitenkaan lataaminen ei onnistu, syynä näyttää olevan että jakson xml.osoitetta ei voida avata. Koitin parilla eri videolla tätä mutta sama ongelma jatkuu. Ohessa screeshot sovelluksesta
<img width="413" alt="ruutu lataaja" src="https://user-images.githubusercontent.com/70053114/90951625-20b84b00-e465-11ea-9b22-15fc15fbda81.png">

**Comment by tinopucci** [comment]
Kyllä tää toimi ihan ohjeistuksen mukaan.
Oliko @jypinen wget ladattu vai oliko wget'in polku jäänyt määrittämättä?

**Comment by jeppoo1** [comment]
Minulla on sama ongelma, kansio siirretty käyttäjänimen alle, ajan .bat-filen administraattorina ja koko ajan tulee sama virheilmoitus. **@tinopucci tai @untoor osaatteko sanoa minkä kohdan olen missannut ohjeistuksesta?**

Latasin myös wget:n reposta ensin rar-tiedoston mukana ja sitten vielä erikseen ja siirsin kansioon. Kumpikaan näistä ei auttanut. **Mitä wget-tiedostolle pitäisi tehdä?**
Vai pitääkö bat-fileen käydä muokkaamassa jokin polku uudelleen notepadin kautta...?

Tässä vielä virheilmoitus:
"'
Jakson osoite: https://www.ruutu.fi/video/3712933

Tiedostonimi: testi

Aloitetaan lataamaan videota...

'..\wget.exe' is not recognized as an internal or external command,
operable program or batch file.
testi

HUOM! Jakson html-osoitetta ei havaittu!

'..\wget.exe' is not recognized as an internal or external command,
operable program or batch file.

'..\wget.exe' is not recognized as an internal or external command,
operable program or batch file.
testi

HUOM! Jakson xml-osoitetta ei havaittu!
FINDSTR: Cannot open xml.txt
FINDSTR: Cannot open xml.txt

HUOM! Videon osoitetta ei havaittu! Videota ei voi ladata.

Videossa saattaa olla DRM-suojaus aktiivinen. Kokeile toista videota.

Jos kyseessä on podcast, kokeile toista jaksoa.
"

**Comment by untoor** [comment]
@jeppoo1 Moro, itsellä toimii lataus ilman ongelmia. Tarkistin niin polut on ihan kunnossa. Adminina ei tarvitse ohjelmaa ajaa.
