### ISSUE TITLE
Latausongelma - liittyykö autentikointiin?

### ISSUE THREAD

**Issue by Automauto** [untoor/Ruutu-lataaja#3]
Hei, kiitos hyvästä softaideasta. Toivottavasti tämä kysymys ei ole ihan päälö :) Koitin ladata maksusisältöihin kuuluvan jakson, joka näkyy ok selaimellani, kun olen kirjautuneena Ruutu+:aan. BAT näyttää virheilmoituksen: ECHO. &ECHO Jos saat taman infon, elokuvassa tai videossa on DRM-suojaus aktiivinen. Kysymykseni on, onnistuuko tällaisen jakson lataus jotenkin niin, että lataajaan syötetään oma käyttäjätunnus ja salasana eli hoidetaan autentikointi Ruutu+:n suuntaan?

**Comment by untoor** [comment]
@Automauto Morjes, on asiallinen kysymys. Ja pahoittelut viivästyksestä, ei tule ilmoituksia lainkaan täältä vaikka asetus kunnossa.... 
Sinne osoiteriville lisätään henk.koht. token urlin loppuun joka avaa sen varsinaisen lataus-urlin, ja se token on koodissa itsessään sisällä. Ongelma on vaan siinä, kun joka kerta kirjautuessa Ruutuun, se Ruutu+ -token vaihtuu, niin se edellinen token toimii X-ajan, 3pv-1,5vk. 
Niin näin ollen se token täytyy aina manuaalisesti vaihtaa (silloin kun ei enää lataa) jotta Ruutu+ -videot lähtee latautuun, ilmaiset videot latautuu ilman tokenia.

Olen sitä pähkäillyt miten saisi lisättyä skriptiin autom. kirjautuminen ruutuun kun avaa ohjelman, en ole varma toimisiko se. Hyvä idea silti ja yritetään saada jonkinlainen versio tulemaan jossain vaiheessa.

**Comment by naftis** [comment]
@untoor Moi, kiitti työkalusta. Mietin että olisiko jotkut ohjeet paikallaan miten token hankitaan ja mihin se laitetaan? Itelle ei ainakaan ihan 5 minuutissa auennut, mutta yritän selvitellä :)

**Comment by untoor** [comment]
@naftis Moro, en tiedä miten ahkerasti Sanoman väki tutkailee näitä ohjelmia mitä on tarjolla ja että piilottavatko he sitten tärkeimmät osoitteet sivustoiltansa. Periaatteessa sen ohjeen voisin kirjoittaa koska lähdekoodi on vapaata kaikille ja sieltä se haetaan. 
Vähän 50/50 tilanne.

**Comment by naftis** [comment]
@untoor Voisiko tässä issuessa olla jotkut teknisemmät ohjeet? Suurin piirtein sen requestin tai keksin tiedot mistä token pitäisi kaivaa. Oma veikkaus on, että jos ohjeita ei tuo etusivulle (ominaisuutta ei mainosteta eikä käyttäjiä kannusteta käyttämään sitä), vaan ohjeet löytyy vain tonkimalla, niin suhtautuminen Sanoman puolelta lienee suopeampi.

disclaimer: En ole lakimies enkä kannusta väärinkäyttämään Sanoman palveluita :)

**Comment by untoor** [comment]
@naftis Jjoo sellaiset suuripiirteiset, onnistuu. Ja aikalailla noin, on hyvä pitää ne ohjeet hivenen pimennossa mutta kuitenkin löydettävissä, esim. vaikka kansion mukana tulevassa ohjeessa. Tonne bat-filuun pitää käydä itse se token vielä vaihtamassa, hmm mietin et miten sen sais järkevämmäksi kun avaa ohjelman. Kun mitään pingausta ei pysty suorittaan palvelimelle. 

Joo näin oli. Ja kun ne korjattiin, meni pitkän aikaa ennenkuin saivat selville et mitä on muutettu.

**Comment by untoor** [comment]
@naftis Nyt olisi uusi versio saatavilla. (ja mukana ohjeet tokenin löytämiseen)

**Comment by Automauto** [comment]
Suurkiitos päivityksestä, testaan uutta versiota heti kun ehtii.

**Comment by Dimppu** [comment]
> @naftis Nyt olisi uusi versio saatavilla. (ja mukana ohjeet tokenin löytämiseen)

Kiitosta vaan täältäkin suunnalta. Hienoa työtä. Kiinnostaisi suuresti ohjeet aanikirjoihin, niitä tulee kulutettua jonkin verran.
En löytänyt yv:tä mistään, joten.. deythoujspu@hotmail.com. Kiitos vielä.
