### ISSUE TITLE
Sanoo että "The system cannot find the path specified."

### ISSUE THREAD

**Issue by hukeboi** [untoor/Ruutu-lataaja#4]
Yritän käyttää mutta sanoo tota samaa kokoajan.

![testi](https://user-images.githubusercontent.com/79796932/109421712-22009c80-79e1-11eb-9a28-2138e7021494.JPG)

**Comment by hukeboi** [comment]
Alkoi toimia kun kävin vaihtamassa tuolta BAT tiedostosta kaikki %username% kohdat mun omaan usernameen.

**Comment by untoor** [comment]
@hukeboi Moro, okei hyvä juttu. Ohjelman pitäisi toimia ilman korjauksia, siksi %username% -asetus on siellä.
