### ISSUE TITLE
Ääniraita

### ISSUE THREAD

**Issue by quenthal** [untoor/Ruutu-lataaja#6]
Onkohan Ruutu+ -materiaalissa monikanavaääntä eli muuta kuin stereoääntä tarjolla, vai onko tämä konffattavissa jotenkin ffmpegin parametreillä?

**Comment by untoor** [comment]
@quenthal Hyvä kysymys, tietääkseni joissakin on monikanavaääni tarjolla, mutta harvassa. Sen pitäisi pystyä ffmpeg:llä muuntamaan. Ainakin monoääneksi onnistuu.

**Comment by Jukkis210** [comment]
Miten saisi vaihdettua ffmpeg riviin pätkän jolla saisi isomman ääni bitraten kuin 128?
Aika nyyppä tän asian kanssa :)

**Comment by quenthal** [comment]
> @quenthal Hyvä kysymys, tietääkseni joissakin on monikanavaääni tarjolla, mutta harvassa. Sen pitäisi pystyä ffmpeg:llä muuntamaan. Ainakin monoääneksi onnistuu.

Mietin enemmän, että eihän ffmpegin osalta nyt käytössä olevat parametrit muuta ääntä lainkaan lähteeseen nähden? Ts. haluaisin varmistaa jokaisen materiaalin kohdalla sen, että ääniraita on lähteeseen nähden paras mahdollinen (oli sitten kyse bitratesta tai ääniformaatista).

**Comment by untoor** [comment]
> Miten saisi vaihdettua ffmpeg riviin pätkän jolla saisi isomman ääni bitraten kuin 128? Aika nyyppä tän asian kanssa :)

Lisäät siihen riviin ennen -c copy-kohtaa _-b:a 384k_ ja tuohon 384 voit vaihtaa haluamasi bitraten. 384 on 5.1 surround, 320 taas mp3-tasoista laatua.
En satavarmaksi tiedä miten tämä muunnos ylöspäin onnistunee, eli millainen ääni on lopputulemana. Rätiseekö tms.

**Comment by Jukkis210** [comment]
Kiitoksia tiedosta. Minäpä hieman alan kokeilemaan :)

**Comment by untoor** [comment]
> > @quenthal Hyvä kysymys, tietääkseni joissakin on monikanavaääni tarjolla, mutta harvassa. Sen pitäisi pystyä ffmpeg:llä muuntamaan. Ainakin monoääneksi onnistuu.
> 
> Mietin enemmän, että eihän ffmpegin osalta nyt käytössä olevat parametrit muuta ääntä lainkaan lähteeseen nähden? Ts. haluaisin varmistaa jokaisen materiaalin kohdalla sen, että ääniraita on lähteeseen nähden paras mahdollinen (oli sitten kyse bitratesta tai ääniformaatista).
> 
> EDIT: sehän on jo -c copy :)

Ei muuta, et ffmpeg lataa audion sen laatuisena kuin se on videossa. Liekö tässä sit Ruudussa oleva asetus mikä pakottaa äänenlaadun pienemmälle bittivirralle... 
Toi -c copy on vaan se että ladatuista palasista luodaan lopuksi mp4-tiedosto. 
Kuten tuossa edelliselle neuvoin niin säkin voit lisätä ffmpeg riviin osuuden jolloinka saat ne äänet aina samalla ja paremmalla laadulla. -b:a 384k on esimerkiksi 5.1 surroundin laatu.

**Comment by untoor** [comment]
> Kiitoksia tiedosta. Minäpä hieman alan kokeilemaan :)

Juu. Infoile vaikka miten on käynyt. :)

**Comment by Jukkis210** [comment]
Kokeilin juuri mutta eipä näytä olevan mitään vaikutusta. Pistin sen näin:

TITLE Ladataan %info%... " %echo_line_string% "
"%..%\ffmpeg.exe" -i "%auth_url%" -v quiet -progress - -y -b:a 320k -c copy "C:\Users\%USERNAME%\%echo_line_string%.mp4" || "%..%\ffmpeg.exe" -i "%audio_url%" -v quiet -stats "C:\Users\%USERNAME%\%echo_line_string%.mp3"
TITLE %program_name%

**Comment by untoor** [comment]
> Kokeilin juuri mutta eipä näytä olevan mitään vaikutusta. Pistin sen näin:
> 
> EDIT1: No nyt alkoi toimimaan jotenkin erilailla. Nyppäsin koko -c copy kohdan hedvekkiin niin alkoi bitratet muuttumaan :) EDIT2: Mutta videon ratet tippuu?

Ok kiitos. Tutkailen ja testaan huomenna.

**Comment by untoor** [comment]
> Kokeilin juuri mutta eipä näytä olevan mitään vaikutusta. Pistin sen näin:
> 
> EDIT1: No nyt alkoi toimimaan jotenkin erilailla. Nyppäsin koko -c copy kohdan hedvekkiin niin alkoi bitratet muuttumaan :) EDIT2: Mutta videon ratet tippuu?

Noniin testailin itsekin, sori vähän venähti aikataulullisesti. 
Mutta joo tosiaan pelkkä _**-b:a**_ ei teekään ääniraidalle mitään muutosta. 
Testasin myös et nakkaa -c copyn pois ja juu videon ratet tippuu. Johtunee siitä että ffmpeg ottaa jonkinlaista laatua kun sille ei ole määritetty mitään arvoa. -c copy tuottaa videosta ja äänestä sen max oletusarvon. 
Laitan tähän kaksi esimerkkiä, voin myös päivittää tän ohjelman isommalle äänibitratelle valmiiksi ja julkaista?

Koodissa -c copy kohtaan tulee muutos: _**-c:v copy -b:a 320k**_ 
Jos haluaa 5.1 surroundin niin silloin tulee: _**-c:v copy -ac 6 -b:a 384k**_

**Comment by untoor** [comment]
> > @quenthal Hyvä kysymys, tietääkseni joissakin on monikanavaääni tarjolla, mutta harvassa. Sen pitäisi pystyä ffmpeg:llä muuntamaan. Ainakin monoääneksi onnistuu.
> 
> Mietin enemmän, että eihän ffmpegin osalta nyt käytössä olevat parametrit muuta ääntä lainkaan lähteeseen nähden? Ts. haluaisin varmistaa jokaisen materiaalin kohdalla sen, että ääniraita on lähteeseen nähden paras mahdollinen (oli sitten kyse bitratesta tai ääniformaatista).
> 
> EDIT: sehän on jo -c copy :)

Oikeassa olet, tutkailin tätä lisää ja tarkemmin. Pahoittelut siis minun osaltani kun sanoin väärin. 
Mutta jos haluat muutoksia siihen oletukseen niin muokkaa koodissa -c copy kohtaan seuraavasti: _**-c:v copy -b:a 320k**_ , tai minkä vaan äänenlaadun halua siihen.
