### ISSUE TITLE
Linux ja Mac tuki

### ISSUE THREAD

**Issue by nikdikpik** [untoor/Ruutu-lataaja#7]
Crossplatform versio olisi houkuttelevampi. Ei jaksais alkaa windowssia tämän takia asentelemaan.

**Comment by untoor** [comment]
> Crossplatform versio olisi houkuttelevampi. Ei jaksais alkaa windowssia tämän takia asentelemaan.

Applen käyttistä en ole koskaan käyttänyt joten ei ole kokemusta sille ohjelmoinnista. Virtualboxilla voisin ajella sitä mutta vie kuitenkin tovin kun saisin ohjelman valmiiksi. 
Linuxillehan on saatavilla Wine mutta se ei taida tukea .bat:ia? Vai tukeeko nykyisin?

**Comment by matti** [comment]
ffmpeg riittää: https://github.com/ytdl-org/youtube-dl/issues/21031#issuecomment-1017828446
