### ISSUE TITLE
En pysty

### ISSUE THREAD

**Issue by Jukkis210** [untoor/Ruutu-lataaja#8]
Enään lataamaan + sisältöä.
Onkohan Ruutu muuttanut jotain koodissa?
Ja juu on tilaus voimassa :)

**Comment by untoor** [comment]
Kiitos viestistä, siellä on tod.näk tullu muutoksia. Ite lopetin juur 1.10. tilauksen kun päätty alennus, koittanu löytää uutta. 
Pyrin ratkaiseen latausongelmat tässä vklp aikana.

**Comment by untoor** [comment]
@Jukkis210 Hommasin uuden tilauksen ja itsellä lähti latautuun Katiskan jaksot, kun otin testiksi. Mitään muutoksia ei ole koodissa ilmennyt joten epäilen että sun käyttäjätoken on tullu vanhaksi. Se kun toimii X-ajan. Tästä maininta infossa. 
Jos ongelma on jonkin muunlainen niin pistä linkkiä missä ongelma esiintyy!

**Comment by Jukkis210** [comment]
Onko chrome sitten jotenkin päivittynyt kun en löydä enään ollenkaan gatling_token kohtaa?
token löytyy mutta ei vaan anna ladata sillä.

**Comment by untoor** [comment]
Käytän itse firefoxia ja sillä löytyy, joten en osaa sanoa. Pitääpi huomenna tutkiskella. 
Siellä on muistaakseni kaksi gatling_token-tekstiä ja se toinen on vain oikea.

**Comment by untoor** [comment]
@Jukkis210 Token löytyy chromessa web-työkaluissa *Sovellus*-kohdasta, ottaa sen ja vasemmalle tulee pieni ikkuna, sieltä *Tallennustila* jossa Evästeet ja sitten avautuu listaus. Ja siinä. 
Ilmottele miten käy/kävi.

**Comment by Jukkis210** [comment]
YES,

Kiitoksia kovasti. Nyt toimii :D
