### ISSUE TITLE
Supla

### ISSUE THREAD

**Issue by mproffa** [untoor/Ruutu-lataaja#9]
Hei! Kaipailisin ohjeita Sublasta lataamiseen. Oon laittanut mailia taannoin.

**Comment by untoor** [comment]
Moro, jahas se onkin näemmä mennyt roskapostiin suoraan.... hyvä että infosit tänne! 
Tuo oma lataajani on hieman haastava käyttää, sen kehitys on ollut jäissä jo tovin vaikka toimii kyllä. 
Mutta mulla on antaa sulle laajennusplugi Chromeen joka löytää äänikirjan osoitteen, sun pitää avata jokainen kappale auki mutta latauslinkki ilmestyy heti kun klikkaat auki: https://chrome.google.com/webstore/detail/live-stream-downloader/looepbdllpjgdmkpdcdffhdbmpbcfekj 

Kertoile miten käy.
